#!/usr/bin/env python3
import argparse
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path


class CliError(RuntimeError):
    pass


ROOT = next((p for p in [Path.cwd().resolve(), *Path.cwd().resolve().parents] if (p / ".git").exists()), None)
if ROOT is None:
    raise CliError("not inside a git repository")
DOCS_DIR = ROOT / "docs" / "fdocs"
SKILL_DIR = Path(__file__).resolve().parents[1]
TEMPLATES_DIR = SKILL_DIR / "templates"


def fd_num(name: str) -> int:
    m = re.match(r"fd-?(\d+)", name, re.I)
    return int(m.group(1)) if m else 10**9


def fd_id(n: int) -> str:
    return f"fd{n:03d}" if n < 1000 else f"fd{n}"


def slugify(title: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "_", title.strip()).strip("_")
    return re.sub(r"_+", "_", s).lower() or "untitled"


def scan(docs_dir: Path, warnings: list[str]) -> list[dict[str, str | Path | bool]]:
    out: list[dict[str, str | Path | bool]] = []
    for p, in_archive in [*[(x, False) for x in sorted(docs_dir.glob("*.md"))], *[(x, True) for x in sorted((docs_dir / "archive").glob("*.md"))]]:
        if p.name.startswith("_"):
            continue
        text = p.read_text(encoding="utf-8")
        meta: dict[str, str] = {}
        if text.startswith("---\n"):
            parts = text.split("\n---\n", 1)
            if len(parts) == 2:
                for line in parts[0].splitlines()[1:]:
                    if ":" in line:
                        k, v = line.split(":", 1)
                        meta[k.strip()] = v.strip().strip('"').strip("'")

        planned = meta.get("planned", "").strip()
        closed = meta.get("closed", "").strip()
        for label, value in [("planned", planned), ("closed", closed)]:
            if not value:
                continue
            try:
                datetime.strptime(value, "%Y-%m-%d")
            except ValueError:
                warnings.append(f"{p}: invalid {label} date '{value}' (YYYY-MM-DD)")

        title = meta.get("title", "").strip() or p.stem
        if ":" in title:
            warnings.append(f"{p}: title contains ':'")

        status = "backlog"
        if closed:
            status = "closed"
        elif planned:
            status = "planned"
        elif meta.get("active", "").strip().lower() == "true":
            status = "open"

        fd = re.match(r"(fd-?\d+)", p.stem, re.I)
        out.append(
            {
                "fd": (fd_id(int(re.match(r"fd-?(\d+)", fd.group(1), re.I).group(1))) if fd else p.stem),
                "title": title,
                "status": status,
                "notes": meta.get("notes", "").strip(),
                "closed": closed,
                "path": p,
                "in_archive": in_archive,
            }
        )
    return out


def table(headers: list[str], rows: list[list[str]], empty: list[str]) -> str:
    out = [f"| {' | '.join(headers)} |", f"|{'|'.join(['-' * len(h) for h in headers])}|"]
    if not rows:
        out.append(f"| {' | '.join(empty)} |")
        return "\n".join(out)
    for row in rows:
        out.append(f"| {' | '.join(row)} |")
    return "\n".join(out)


def write_index(index_path: Path, docs: list[dict[str, str | Path | bool]]) -> None:
    active = sorted([d for d in docs if d["status"] in {"open", "planned"}], key=lambda x: fd_num(str(x["fd"])))
    backlog = sorted([d for d in docs if d["status"] == "backlog"], key=lambda x: fd_num(str(x["fd"])))
    closed = sorted(
        [d for d in docs if d["status"] == "closed"],
        key=lambda x: (
            str(x["closed"]) if re.match(r"^\d{4}-\d{2}-\d{2}$", str(x["closed"]) or "") else "0000-00-00",
            fd_num(str(x["fd"])),
        ),
        reverse=True,
    )
    txt = [
        "# Feature Docs Index",
        "",
        f"Generated by `fdocs status` on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## Active Feature Docs",
        "",
        table(
            ["FD", "Title", "Status", "Notes"],
            [[str(d["fd"]), str(d["title"]), str(d["status"]), str(d["notes"] or "-")] for d in active],
            ["-", "-", "-", "No active items"],
        ),
        "",
        "## Backlog",
        "",
        table(
            ["FD", "Title", "Notes"],
            [[str(d["fd"]), str(d["title"]), str(d["notes"] or "-")] for d in backlog],
            ["-", "-", "No backlog items"],
        ),
        "",
        "## Closed",
        "",
        table(
            ["FD", "Title", "Closed", "Notes"],
            [[str(d["fd"]), str(d["title"]), str(d["closed"] or "-"), str(d["notes"] or "-")] for d in closed],
            ["-", "-", "-", "No closed items"],
        ),
        "",
    ]
    index_path.write_text("\n".join(txt), encoding="utf-8")


def cmd_new(title: str) -> int:
    t = title.strip()
    if not t:
        raise CliError("title is required")
    root, docs_dir = ROOT, DOCS_DIR
    archive_dir = docs_dir / "archive"
    template = docs_dir / "_TEMPLATE.md"
    docs_dir.mkdir(parents=True, exist_ok=True)
    archive_dir.mkdir(parents=True, exist_ok=True)
    if not template.exists():
        raise CliError(f"missing template: {template}")

    max_num = 0
    for p in list(docs_dir.glob("*.md")) + list(archive_dir.glob("*.md")):
        if p.name.startswith("_"):
            continue
        m = re.match(r"fd-?(\d+)", p.stem, re.I)
        if m:
            max_num = max(max_num, int(m.group(1)))
    fd = fd_id(max_num + 1)
    out = docs_dir / f"{fd}_{slugify(t)}.md"
    if out.exists():
        raise CliError(f"file already exists: {out}")

    body = template.read_text(encoding="utf-8")
    safe_title = slugify(t).replace("_", " ")
    body = re.sub(r'(?m)^title:\s*.*$', f'title: "{safe_title}"', body, count=1)
    out.write_text(body, encoding="utf-8")

    warnings: list[str] = []
    write_index(docs_dir / "_INDEX.md", scan(docs_dir, warnings))

    print(f"fdoc created: {out.relative_to(root)}")
    return 0


def cmd_init() -> int:
    docs_dir = DOCS_DIR
    archive_dir = docs_dir / "archive"
    dev_guide_dir = ROOT / "docs" / "dev_guide"
    docs_dir.mkdir(parents=True, exist_ok=True)
    archive_dir.mkdir(parents=True, exist_ok=True)
    dev_guide_dir.mkdir(parents=True, exist_ok=True)

    created: list[str] = []
    updated: list[str] = []
    skipped: list[str] = []

    tpl_src = TEMPLATES_DIR / "_TEMPLATE.md"
    tpl_dst = docs_dir / "_TEMPLATE.md"
    if not tpl_src.exists():
        raise CliError(f"missing template: {tpl_src}")
    if not tpl_dst.exists():
        tpl_dst.write_text(tpl_src.read_text(encoding="utf-8"), encoding="utf-8")
        created.append(str(tpl_dst.relative_to(ROOT)))
    else:
        skipped.append(f"exists: {tpl_dst.relative_to(ROOT)}")

    changelog_src = TEMPLATES_DIR / "CHANGELOG.md"
    changelog_dst = ROOT / "CHANGELOG.md"
    if changelog_src.exists() and not changelog_dst.exists():
        changelog_dst.write_text(changelog_src.read_text(encoding="utf-8"), encoding="utf-8")
        created.append(str(changelog_dst.relative_to(ROOT)))
    elif changelog_dst.exists():
        skipped.append(f"exists: {changelog_dst.relative_to(ROOT)}")

    dev_guide_tpl_dir = TEMPLATES_DIR / "dev_guide"
    if dev_guide_tpl_dir.exists():
        for src in sorted(dev_guide_tpl_dir.glob("*.md")):
            dst = dev_guide_dir / src.name
            if dst.exists():
                skipped.append(f"exists: {dst.relative_to(ROOT)}")
            else:
                dst.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
                created.append(str(dst.relative_to(ROOT)))

    agents_src = TEMPLATES_DIR / "AGENTS_MD_ADDITIONAL.md"
    agents_dst = ROOT / "AGENTS.md"
    if agents_src.exists():
        agents_existed = agents_dst.exists()
        current = agents_dst.read_text(encoding="utf-8") if agents_existed else "# AGENTS\n"
        changed = False

        snippet = agents_src.read_text(encoding="utf-8").strip()
        if snippet in current:
            skipped.append(f"exists: fdocs block in {agents_dst.relative_to(ROOT)}")
        else:
            heading = next((line.strip() for line in snippet.splitlines() if line.strip()), "")
            heading_exists = bool(re.search(rf"(?m)^{re.escape(heading)}\s*$", current)) if heading.startswith("## ") else False
            if heading_exists:
                skipped.append(f"exists: fdocs heading in {agents_dst.relative_to(ROOT)}")
            else:
                current = current.rstrip() + "\n\n" + snippet + "\n"
                changed = True

        if changed:
            agents_dst.write_text(current.rstrip() + "\n", encoding="utf-8")
            rel_agents = str(agents_dst.relative_to(ROOT))
            if agents_existed:
                updated.append(rel_agents)
            else:
                created.append(rel_agents)

    warnings: list[str] = []
    write_index(docs_dir / "_INDEX.md", scan(docs_dir, warnings))
    created.append(str((docs_dir / "_INDEX.md").relative_to(ROOT)))

    print("fdocs initialized")
    if created:
        print("created:")
        for p in created:
            print(f"- {p}")
    if updated:
        print("updated:")
        for p in updated:
            print(f"- {p}")
    if skipped:
        print("skipped:")
        for p in skipped:
            print(f"- {p}")
    if warnings:
        print("warnings:")
        for w in warnings:
            print(f"- {w}")
    return 0


def cmd_close(fd: str, notes: str, date: str) -> int:
    token = fd.strip()
    if re.fullmatch(r"\d+", token):
        n = int(token)
        token = fd_id(n)
    m_token = re.fullmatch(r"fd-?(\d+)", token, re.I)
    if not m_token:
        raise CliError("fd must be like 1, 001, fd001, fd-001, or fd1000")
    n = int(m_token.group(1))
    token = fd_id(n)
    try:
        datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        raise CliError("date must be YYYY-MM-DD")

    docs_dir = DOCS_DIR
    archive_dir = docs_dir / "archive"
    archive_dir.mkdir(parents=True, exist_ok=True)

    matches = sorted(
        p for p in docs_dir.glob("*.md") if not p.name.startswith("_") and (m := re.match(r"fd-?(\d+)", p.stem, re.I)) and int(m.group(1)) == n
    )
    if not matches:
        archived = sorted(
            p
            for p in archive_dir.glob("*.md")
            if not p.name.startswith("_") and (m := re.match(r"fd-?(\d+)", p.stem, re.I)) and int(m.group(1)) == n
        )
        if archived:
            raise CliError(f"already archived: {archived[0].relative_to(ROOT)}")
        raise CliError(f"fdoc not found: {token}")
    if len(matches) > 1:
        raise CliError(f"multiple files match {token}")
    src = matches[0]

    text = src.read_text(encoding="utf-8")
    body = text
    if text.startswith("---\n") and "\n---\n" in text:
        raw_front, body = text[4:].split("\n---\n", 1)
        lines = raw_front.splitlines()
    else:
        lines = []

    updates = {
        "active": "false",
        "planned": "",
        "closed": date,
    }
    if notes.strip():
        updates["notes"] = notes.strip()

    def _q(v: str) -> str:
        return v.replace("\\", "\\\\").replace('"', '\\"')

    seen: set[str] = set()
    new_lines: list[str] = []
    for line in lines:
        if ":" not in line:
            new_lines.append(line)
            continue
        k, _ = line.split(":", 1)
        key = k.strip()
        if key in updates:
            new_lines.append(f'{key}: "{_q(updates[key])}"')
            seen.add(key)
        else:
            new_lines.append(line)
    for key in ["active", "planned", "closed", "notes"]:
        if key in updates and key not in seen:
            new_lines.append(f'{key}: "{_q(updates[key])}"')

    src.write_text("---\n" + "\n".join(new_lines) + "\n---\n\n" + body.lstrip("\n"), encoding="utf-8")

    dst = archive_dir / src.name
    if dst.exists():
        raise CliError(f"archive target exists: {dst.relative_to(ROOT)}")
    src.rename(dst)

    warnings: list[str] = []
    write_index(docs_dir / "_INDEX.md", scan(docs_dir, warnings))

    print(f"fdoc closed: {token}")
    print(f"archived: {dst.relative_to(ROOT)}")
    print(f"index updated: {(docs_dir / '_INDEX.md').relative_to(ROOT)}")
    if warnings:
        print("warnings:")
        for w in warnings:
            print(f"- {w}")
    return 0


def cmd_status(grooming: bool) -> int:
    docs_dir = DOCS_DIR
    if not docs_dir.exists():
        raise CliError(f"missing directory: {docs_dir}")
    (docs_dir / "archive").mkdir(parents=True, exist_ok=True)

    warnings: list[str] = []
    docs = scan(docs_dir, warnings)

    moved: list[str] = []
    if grooming:
        for d in docs:
            if d["in_archive"] or d["status"] != "closed":
                continue
            src = Path(str(d["path"]))
            dst = docs_dir / "archive" / src.name
            if dst.exists():
                warnings.append(f"skip move (target exists): {src} -> {dst}")
                continue
            src.rename(dst)
            moved.append(f"{src.relative_to(docs_dir)} -> archive/{dst.name}")

    docs = scan(docs_dir, warnings)
    write_index(docs_dir / "_INDEX.md", docs)

    active = sorted([d for d in docs if d["status"] in {"open", "planned"}], key=lambda x: fd_num(str(x["fd"])))
    n_open = sum(1 for d in active if d["status"] == "open")
    n_planned = sum(1 for d in active if d["status"] == "planned")

    if grooming and moved:
        print("## Grooming")
        for m in moved:
            print(f"- moved: {m}")
        print()
    if warnings:
        print("## Grooming Warnings")
        for w in warnings:
            print(f"- {w}")
        print()

    print("## Active Feature Designs")
    print()
    print(
        table(
            ["FD", "Title", "Status", "Notes"],
            [[str(d["fd"]), str(d["title"]), str(d["status"]), str(d["notes"] or "-")] for d in active],
            ["-", "-", "-", "No active items"],
        )
    )
    print()
    print(f"**Total:** {len(active)} active items ({n_open} open, {n_planned} planned)")
    print(f"\nIndex updated: {docs_dir / '_INDEX.md'}")
    return 0


def cmd_explore() -> int:
    docs_dir = DOCS_DIR
    if not docs_dir.exists():
        raise CliError(f"missing directory: {docs_dir}")
    (docs_dir / "archive").mkdir(parents=True, exist_ok=True)

    warnings: list[str] = []
    docs = scan(docs_dir, warnings)
    active = sorted([d for d in docs if d["status"] in {"open", "planned"}], key=lambda x: fd_num(str(x["fd"])))
    backlog = [d for d in docs if d["status"] == "backlog"]
    closed = [d for d in docs if d["status"] == "closed"]
    archived_count = sum(1 for d in docs if d["in_archive"])

    def git_out(args: list[str]) -> tuple[int, str]:
        proc = subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True)
        return proc.returncode, proc.stdout.strip()

    rc, branch = git_out(["rev-parse", "--abbrev-ref", "HEAD"])
    branch = branch if rc == 0 and branch else "unknown"

    rc, recent = git_out(["log", "--oneline", "-n", "10"])
    recent_commits = [x for x in recent.splitlines() if x.strip()] if rc == 0 else []

    rc, changed = git_out(["log", "--name-only", "--pretty=format:", "-n", "5"])
    changed_files: list[str] = []
    if rc == 0:
        seen: set[str] = set()
        for f in [x.strip() for x in changed.splitlines() if x.strip()]:
            if f not in seen:
                seen.add(f)
                changed_files.append(f)

    rc, dirty_raw = git_out(["status", "--short"])
    dirty = [x for x in dirty_raw.splitlines() if x.strip()] if rc == 0 else []

    print("## Fdocs Status")
    print()
    print(
        table(
            ["FD", "Title", "Status", "Notes"],
            [[str(d["fd"]), str(d["title"]), str(d["status"]), str(d["notes"] or "-")] for d in active[:12]],
            ["-", "-", "-", "No active items"],
        )
    )
    print()
    print(
        f"Counts: active={len(active)} (open={sum(1 for d in active if d['status']=='open')}, planned={sum(1 for d in active if d['status']=='planned')}), "
        f"backlog={len(backlog)}, closed={len(closed)}, archived={archived_count}"
    )

    print("\n## Recent Activity")
    print()
    print(f"- Branch: {branch}")
    print(f"- Working tree: {'dirty' if dirty else 'clean'}")

    print("\nRecent commits:")
    if recent_commits:
        for c in recent_commits[:8]:
            print(f"- {c}")
    else:
        print("- (none)")

    print("\nFiles in recent commits:")
    if changed_files:
        for f in changed_files[:12]:
            print(f"- {f}")
    else:
        print("- (none)")

    if dirty:
        print("\nUncommitted changes:")
        for line in dirty[:12]:
            print(f"- {line}")

    print("\n## Quick Reference")
    print()
    print(
        table(
            ["Item", "Value"],
            [
                ["Project", ROOT.name],
                ["Branch", branch],
                ["Active FDs", str(len(active))],
                ["Backlog", str(len(backlog))],
                ["Closed", str(len(closed))],
            ],
            ["-", "-"],
        )
    )

    if warnings:
        print("\n## Warnings")
        print()
        for w in warnings:
            print(f"- {w}")

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(prog="fdocs", description="Feature Docs utility")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("init", help="Initialize docs/fdocs structure and seed files")
    p_status = sub.add_parser("status", help="Regenerate docs/fdocs/_INDEX.md and print active status")
    p_status.add_argument("--grooming", action="store_true", help="Move closed fdocs into docs/fdocs/archive before generating status")
    p_new = sub.add_parser("new", help="Create a new fdoc from docs/fdocs/_TEMPLATE.md")
    p_new.add_argument("title", help="FDoc title")
    p_close = sub.add_parser("close", help="Close an fdoc and move it to docs/fdocs/archive")
    p_close.add_argument("fd", help="FD id (e.g. 1, 001, fd001, fd-001)")
    p_close.add_argument("--notes", default="", help="Optional closing notes")
    p_close.add_argument("--date", default=datetime.now().strftime("%Y-%m-%d"), help="Closed date (YYYY-MM-DD)")
    sub.add_parser("explore", help="Print fdocs status and recent repo activity")
    args = parser.parse_args()
    try:
        if args.cmd == "init":
            return cmd_init()
        if args.cmd == "status":
            return cmd_status(args.grooming)
        if args.cmd == "new":
            return cmd_new(args.title)
        if args.cmd == "close":
            return cmd_close(args.fd, args.notes, args.date)
        if args.cmd == "explore":
            return cmd_explore()
        raise CliError(f"unknown command: {args.cmd}")
    except CliError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
